### ISSUE TITLE
asan fails on Windows with the load_libsndfile example only when building under clang if invoked with a .flac file

### ISSUE THREAD

**Issue by ahicks92** [synthizer/synthizer#72]
Not putting this in the 1.0 milestone because it seriously looks for all the world like a false positive.  Libsndfile apparently doesn't like flac files so it throws an error, then asan fails.  MSVC doesn't,neither does GCC under WSL.  I think maybe this is some sort of MSVC compatibility thing.  Output:

```
(base) PS C:\projects\in_progress\synthizer\build> .\load_libsndfile.exe ..\corpus\ball.flac ..\sndfile.dll
debug(background-thread 1) Background thread started
=================================================================
==14420==ERROR: AddressSanitizer: access-violation on unknown address 0x00e4b9baefa0 (pc 0x00e4b9baefa0 bp 0x00e4b9baf1e0 sp 0x00e4b9bac6c8 T0)
    #0 0xe4b9baef9f  (<unknown module>)
    #1 0x7ff7971803eb in synthizer::getDecoderForStream(class std::shared_ptr<class synthizer::ByteStream>) C:\projects\in_progress\synthizer\src\decoding.cpp:39
    #2 0xe4b9bae81f  (<unknown module>)
    #3 0x7ff8eef47033  (C:\WINDOWS\System32\KERNEL32.DLL+0x180017033)
    #4 0xe4b9baf15f  (<unknown module>)
    #5 0xe4b9bac74f  (<unknown module>)
    #6 0xe4b9badfcf  (<unknown module>)
    #7 0x7ff79756fcbb in __FrameHandler3::CxxCallCatchBlock(struct _EXCEPTION_RECORD *) d:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\frame.cpp:1521
    #8 0x7ff8ef6b1505  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x1800a1505)
    #9 0x7ff79717ff0c in synthizer::getDecoderForStream(class std::shared_ptr<class synthizer::ByteStream>) C:\projects\in_progress\synthizer\src\decoding.cpp:31
    #10 0x7ff79707d00b in syz_createBufferFromStreamHandle::<unnamed-tag>::operator() C:\projects\in_progress\synthizer\src\buffer.cpp:185
    #11 0x7ff797077a9d in synthizer::cWrapper<`lambda at C:\projects\in_progress\synthizer\src\buffer.cpp:182:2' &> C:\projects\in_progress\synthizer\include\synthizer\c_api.h
pp:21
    #12 0x7ff7970774b2 in syz_createBufferFromStreamHandle C:\projects\in_progress\synthizer\src\buffer.cpp:188
    #13 0x7ff7970719f9 in main C:\projects\in_progress\synthizer\examples\load_libsndfile.c:43
    #14 0x7ff797533d43 in __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #15 0x7ff8eef47033  (C:\WINDOWS\System32\KERNEL32.DLL+0x180017033)
    #16 0x7ff8ef662650  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x180052650)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: access-violation (<unknown module>)
==14420==ABORTING
(base) PS C:\projects\in_progress\synthizer\build>
```

**Comment by ahicks92** [comment]
I'm ripping out libsndfile so this is no longer applicable.
