### ISSUE TITLE
Possible bug with `syz_eventDeinit`

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#75]
In my [dart bindings](https://github.com/chrisnorman7/dart_synthizer), if I use `syz_eventDeinit` to deinit an event at the end of my `Context.getEvent` method, it seems to free the objects associated with that event.

It could of course be somewhere in my code, or a bug in dart:ffi, or the [ffi package](https://pub.dev/packages/ffi) package, but before going down that particular rabbit hole, I just thought I'd check that you were sure of the Synthizer end.

We're off for a little hike this morning, but I'll probably be able to do more work on this later on and hopefully get you some more details.

For now though, here is the code for my `getEvent` method, for what that's worth.

```dart
  /// Get the next Synthizer event.
  SynthizerEvent? getEvent() {
    SynthizerEvent? value;
    final ptr = calloc<syz_Event>();
    synthizer.synthizer.syz_contextGetNextEvent(ptr, handle.value, 0);
    final sourceHandle = ptr.ref.source;
    switch (ptr.ref.type) {
      case SYZ_EVENT_TYPES.SYZ_EVENT_TYPE_INVALID:
        // No events left.
        break;
      case SYZ_EVENT_TYPES.SYZ_EVENT_TYPE_FINISHED:
        // Something has finished. Let's find out what.
        final SynthizerObject source;
        final type = synthizer.getObjectType(ptr.ref.source);
        switch (type) {
          case ObjectType.bufferGenerator:
            source = BufferGenerator(this)..handle.value = sourceHandle;
            break;
          case ObjectType.buffer:
            source = Buffer(synthizer)..handle.value = sourceHandle;
            break;
          case ObjectType.context:
            source = this;
            break;
          case ObjectType.streamingGenerator:
            source = StreamingGenerator.fromHandle(this, sourceHandle);
            break;
          case ObjectType.noiseGenerator:
            source = NoiseGenerator.fromHandle(this, sourceHandle);
            break;
          case ObjectType.directSource:
            source = DirectSource(this)..handle.value = sourceHandle;
            break;
          case ObjectType.pannedSource:
            source = PannedSource(this)..handle.value = sourceHandle;
            break;
          case ObjectType.source3D:
            source = Source3D(this)..handle.value = sourceHandle;
            break;
          case ObjectType.globalEcho:
            source = GlobalEcho(this)..handle.value = sourceHandle;
            break;
          case ObjectType.globalFdnReverb:
            source = GlobalFdnReverb(this)..handle.value = sourceHandle;
            break;
          default:
            throw SynthizerError(
                'Unhandled object type: $type.', ptr.ref.source);
        }
        value = FinishedEvent(this, source);
        break;
      case SYZ_EVENT_TYPES.SYZ_EVENT_TYPE_LOOPED:
        final type = synthizer.getObjectType(sourceHandle);
        final Generator generator;
        switch (type) {
          case ObjectType.bufferGenerator:
            generator = BufferGenerator(this)..handle.value = sourceHandle;
            break;
          case ObjectType.streamingGenerator:
            generator = StreamingGenerator.fromHandle(this, sourceHandle);
            break;
          case ObjectType.noiseGenerator:
            generator = NoiseGenerator.fromHandle(this, sourceHandle);
            break;
          default:
            throw SynthizerError(
                'unhandled object type: $type.', ptr.ref.source);
        }
        value = LoopedEvent(this, generator);
        break;
      default:
        throw SynthizerError('Unhandled event type.', ptr.ref.type);
    }
    synthizer.synthizer.syz_eventDeinit(ptr);
    return value;
  }
```

Thanks in advance.

**Comment by ahicks92** [comment]
That's possibly correct behavior, because syz_eventDeinit is supposed to be incrementing and decrementing reference counts to the objects.  The typical usage pattern is supposed to be that if you want to keep them around you increment the reference count again.  That said, I'm going to assume you don't have concurrency going on?  If this is all happening on a single thread then you shouldn't see events for already dead objects, which is likely to be a different bug.

I've sort of expected this to prove to be broken one way or another for a while, so it probably actually is.

On a sidenote I'd look to see if dart has dynamic casting because if you set up your inheritance hierarchies right you may be able to get rid of those horrible switch statements by just building a base class and some magic of one sort or another to get to derived classes from it, or having a function that converts any Synthizer handle to a base Synthizer object that code downcasts as needed.

**Comment by chrisnorman7** [comment]
Hi,
Actually they're not as horrible as they look. The VS Code Dart extension
automatically generates them, then I just fill in the code.

No concurrency. Here's the example code that's generating the problem:

```dart
// ignore_for_file: avoid_print
/// Demonstrate events in Synthizer.
import 'dart:ffi';
import 'dart:io';

import 'package:dart_synthizer/dart_synthizer.dart';

Future<void> main() async {
  final synthizer = Synthizer()..initialize();
  final ctx = synthizer.createContext(events: true);
  final buffer = Buffer.fromFile(synthizer, File('sound.wav'));
  final generator = ctx.createBufferGenerator()..setBuffer(buffer);
  final source = ctx.createDirectSource()..addGenerator(generator);
  var looping = true;
  for (var i = 0; i < 5; i++) {
    await Future<void>.delayed(Duration(seconds: 1));
    print(ctx.getEvent());
    print(synthizer.getObjectType(generator.handle.value));
    generator.looping = looping;
    looping = !looping;
  }
  source.destroy();
  generator.destroy();
  ctx.destroy();
  synthizer.shutdown();
}
```

Also, here's the error, because I realised I hadn't included that when I
opened the issue.

```bash
Instance of 'FinishedEvent'
Unhandled exception:
SynthizerError(1): This handle is already dead. Synthizer cannot catch all
cases of invalid handles; change your program to use only valid handles or
risk crashes.
#0      Synthizer.check (package:dart_synthizer/synthizer.dart:64:7)
#1      Synthizer.getObjectType
(package:dart_synthizer/synthizer.dart:385:5)
#2      main
(file:///C:/Users/chris/src/dart_synthizer/example/events_example.dart:18:21)
<asynchronous suspension>
```

Also, I tried setting linger to `false`, and it still errored.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
Yeah, definitely a bug there.  I'll work on it.

**Comment by ahicks92** [comment]
I have added a C example, examples/events.cpp, which should be exactly the same as your dart code.  Unfortunately, that's not triggering it.  If you can build Synthizer locally, can you try and see if it breaks?

I peaked at the Dart bindings, and I didn't see one, but if you have finalizers or whatever on your objects that decrement reference counts then you are possibly ending up with a double decrement: once via syz_eventDeinit, and then again when the event object itself goes out of scope (which is at the end of the print, since you're not assigning it to anything).  Can you quickly confirm that's not what's happening, either by confirming that objects in Dart require explicit destruction or just keeping the event around via a variable for the full duration of when you're using it?

'On an unrelated note your code does have another bug in it, one which would cover up this one if you fixed it now, so maybe let's resolve this first.  As things currently stand, if you're executing event handling concurrently with another thread which deletes an object that an event references, the syz_eventDeinit equivalent will make the handle invalid on the thread doing event handling out from under the event because the temporary reference held by the event will be lost.  In order to properly let events "escape" the time period between getting the event and syz_eventDeinit, you need to increment the references.  This is also true of, e.g., green threads, etc, or just generally anything that might delete a handle unexpectedly somewhere else.  This is why I suspect this issue, whatever it is, doesn't show up in Rust.

**Comment by ahicks92** [comment]
Going to bump this for the sake of seeing if I can get more info to work on it this weekend.

**Comment by chrisnorman7** [comment]
Sorry mate, I need to sit with it to see what I can dig out.

Which branch should I be testing with?

Take care,

Chris Norman

**Comment by ahicks92** [comment]
Master.  And don't worry about it if you don't immediately have the time, just trying to get fixes out promptly where I can before work starts taking a lot of energy again for a while.

**Comment by chrisnorman7** [comment]
I appreciate that mate. I'll do my best, but we're going on holiday
tomorrow, so no promises.

Good luck with work if it's getting busier!

Take care,

Chris Norman

**Comment by chrisnorman7** [comment]
Just to check, do I have to run `syz_eventDeinit` on events with a type of `SYZ_EVENT_TYPE_INVALID`?

The [manual page](https://synthizer.github.io/concepts/events.html) is slightly vague, although it breaks if the above condition is true.

**Comment by chrisnorman7** [comment]
So I have a new `getEvent` method:

```dart
  SynthizerEvent? getEvent() {
    SynthizerEvent? value;
    synthizer.check(synthizer.synthizer
        .syz_contextGetNextEvent(_eventPointer, handle.value, 0));
    if (_eventPointer.ref.type == SYZ_EVENT_TYPES.SYZ_EVENT_TYPE_INVALID) {
      return null;
    }
    final sourceHandle = _eventPointer.ref.source;
    final source = synthizer.getObject(sourceHandle);
    switch (_eventPointer.ref.type) {
      case SYZ_EVENT_TYPES.SYZ_EVENT_TYPE_FINISHED:
        value = FinishedEvent(this, source);
        break;
      case SYZ_EVENT_TYPES.SYZ_EVENT_TYPE_LOOPED:
        value = LoopedEvent(this, source as Generator);
        break;
      default:
        throw SynthizerError('Unhandled event type.', _eventPointer.ref.type);
    }
    synthizer.synthizer.syz_eventDeinit(_eventPointer);
    return value;
  }
```

The example (see below) works if I comment out the `syz_eventDeinit` line, but otherwise I get the error:

```bash
Unhandled exception:
SynthizerError(1): This handle is already dead. Synthizer cannot catch all cases of invalid handles; change your program to use only valid handles or risk crashes.
#0      Synthizer.check (package:dart_synthizer/synthizer.dart:96:7)
#1      Context.getEvent (package:dart_synthizer/context.dart:171:15)
#2      Context.getEvents (package:dart_synthizer/context.dart:197:21)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///C:/Users/chris/src/dart_synthizer/example/events_example.dart)
<asynchronous suspension>
```

In addition, if I wait for that error, then try a call to `syz_handleGetObjectType` using the handle for the current context that is trying to get the events, then I get the same error.

Audio is still playing, so I've clearly not destroyed the context.

I'm inclined to think it's my code rather than yours, but I've no clue where at this point.

**Comment by chrisnorman7** [comment]
Sorry, forgot to post the example:

``dart
// ignore_for_file: avoid_print
/// Demonstrate events in Synthizer.
import 'dart:io';

import 'package:dart_synthizer/dart_synthizer.dart';

Future<void> main() async {
  final synthizer = Synthizer()..initialize();
  final ctx = synthizer.createContext(events: true);
  ctx.getEvents().listen((event) {
    if (event is FinishedEvent) {
      print('Finished: ${event.source}');
    } else if (event is LoopedEvent) {
      print('Looped: ${event.generator}');
    }
  });
  final buffer = Buffer.fromFile(synthizer, File('sound.wav'));
  final generator = ctx.createBufferGenerator(buffer: buffer)..looping = true;
  final source = ctx.createDirectSource()..addGenerator(generator);
  await Future<void>.delayed(Duration(seconds: 3));
  source.destroy();
  generator.destroy();
  ctx.destroy();
  synthizer.shutdown();
  print('Done.');
}
```

**Comment by ahicks92** [comment]
Are you sure your event handler isn't able to run after that delay, when the code hits the destroy lines in main?  That is, can the sequence be delay finished, main destroys objects, event handler listener gets an event?  I suggest starting by just making the delay there 1000 seconds or something ridiculous and see if it still breaks.

I can try to figure out building your example but I'll be honest that I'm not super thrilled by the idea of learning Dart to try debugging this.

**Comment by chrisnorman7** [comment]
Don't blame you for not wanting to build.

Definitely not happening after the await. I've just set the time to 15 seconds, and the second event still causes that.

How hard is it for me to install whatever toolchain you use to write my own in C? I think I know enough C to write out an example testing what I have here.

**Comment by chrisnorman7** [comment]
Ah, ignore that last, I've just seen the example that already does it.

**Comment by chrisnorman7** [comment]
Hi,
Upon running the tests, I get the same error from events.exe:

```bash
debug(background-thread 1) Background thread started
debug(unknown-thread 2) Trying to decode file:..\..\sound.wav
debug(unknown-thread 2) decoder: skipping libsndfile because it isn't loaded
debug(unknown-thread 2) Handler libsndfile returned nullptr. Skipping
debug(unknown-thread 2) Handling stream with handler dr_wav
Got event type 2
syz_handleGetObjectType(&object_type, event.source): Synthizer error code 1 message This handle is already dead. Synthizer cannot catch all cases of invalid handles; change your program to use only valid handles or risk crashes.
debug(background-thread 1) Context shutdown
debug(background-thread 1) Background thread stopped
debug(unknown-thread 3) Deferred free processed 0 frees in a background thread
debug(unknown-thread 2) Library shutdown complete
```

Also, your example doesn't cover the generator looping. Not sure if that might prove useful or not.

**Comment by ahicks92** [comment]
I think this is an obvious question but can you give me your exact compilation commands and confirm you're using MSVC and not Clang?

In any case yeah it's a real bug.  I'll have to figure out how in the world to duplicate this.

**Comment by chrisnorman7** [comment]
OK, firstly, here's the result of building (using the command you emailed to me):

```bash
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Performing Test FILESYSTEM_OK
-- Performing Test FILESYSTEM_OK - Success
-- Found C++17 filesystem support
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/chris/src/dart_synthizer/synthizer/build
```

For completeness, here's the result of running `ninja`:

```bash
[1/96] Building C object CMakeFiles\load_libsndfile.dir\examples\load_libsndfile.c.obj
[2/96] Building C object CMakeFiles\buffer_from_memory.dir\examples\buffer_from_memory.c.obj
[3/96] Building CXX object CMakeFiles\synthizer.dir\src\channel_mixing.cpp.obj
[4/96] Building CXX object CMakeFiles\synthizer.dir\src\error.cpp.obj
[5/96] Building CXX object CMakeFiles\synthizer.dir\src\filter_properties.cpp.obj
[6/96] Building CXX object CMakeFiles\synthizer.dir\src\logging.cpp.obj
[7/96] Building CXX object CMakeFiles\test_random_float.dir\test\random_float.cpp.obj
[8/96] Building CXX object CMakeFiles\synthizer.dir\src\block_buffer_cache.cpp.obj
[9/96] Building CXX object CMakeFiles\synthizer.dir\src\prime_helpers.cpp.obj
[10/96] Building CXX object CMakeFiles\synthizer.dir\src\decoding.cpp.obj
[11/96] Building CXX object CMakeFiles\synthizer.dir\src\hrtf.cpp.obj
[12/96] Building CXX object CMakeFiles\decoding_bench.dir\benchmarks\decoding.cpp.obj
[13/96] Building CXX object CMakeFiles\synthizer.dir\src\noise_generator.cpp.obj
[14/96] Building CXX object CMakeFiles\file_test.dir\file_test.cpp.obj
[15/96] Building CXX object CMakeFiles\events.dir\examples\events.cpp.obj
[16/96] Building CXX object CMakeFiles\synthizer.dir\src\automation_timeline.cpp.obj
[17/96] Building CXX object CMakeFiles\synthizer.dir\src\data\arrays.cpp.obj
[18/96] Building CXX object CMakeFiles\synthizer.dir\src\data\hrtf.cpp.obj
[19/96] Building CXX object CMakeFiles\synthizer.dir\src\stereo_panner.cpp.obj
[20/96] Building CXX object CMakeFiles\synthizer.dir\src\byte_stream.cpp.obj
[21/96] Building CXX object CMakeFiles\synthizer.dir\src\shared_object.cpp.obj
[22/96] Building CXX object CMakeFiles\synthizer.dir\src\base_object.cpp.obj
[23/96] Building CXX object CMakeFiles\synthizer.dir\src\panner_bank.cpp.obj
[24/96] Building CXX object CMakeFiles\synthizer.dir\src\generator.cpp.obj
[25/96] Building CXX object CMakeFiles\synthizer.dir\src\property_internals.cpp.obj
[26/96] Building CXX object CMakeFiles\synthizer.dir\src\spatialization_math.cpp.obj
[27/96] Building CXX object CMakeFiles\synthizer.dir\src\effects\effects.cpp.obj
[28/96] Building CXX object CMakeFiles\synthizer.dir\src\events.cpp.obj
[29/96] Building CXX object CMakeFiles\synthizer.dir\src\memory.cpp.obj
[30/96] Building CXX object CMakeFiles\synthizer.dir\src\c_api.cpp.obj
[31/96] Building CXX object CMakeFiles\wdl.dir\third_party\wdl\WDL\resample.cpp.obj
[32/96] Building CXX object CMakeFiles\synthizer.dir\src\filters\audio_eq_cookbook.cpp.obj
[33/96] Building CXX object CMakeFiles\synthizer.dir\src\decoders\raw_decoder.cpp.obj
[34/96] Building CXX object CMakeFiles\synthizer.dir\src\decoders\flac.cpp.obj
[35/96] Building CXX object CMakeFiles\synthizer.dir\src\decoders\libsndfile.cpp.obj
[36/96] Building CXX object CMakeFiles\synthizer.dir\src\biquad.cpp.obj
[37/96] Building C object CMakeFiles\basic_stream_handle.dir\examples\basic_stream_handle.c.obj
[38/96] Building CXX object CMakeFiles\synthizer.dir\src\decoders\mp3.cpp.obj
[39/96] Building CXX object CMakeFiles\synthizer.dir\src\routable.cpp.obj
[40/96] Building CXX object CMakeFiles\synthizer.dir\src\stream_handle.cpp.obj
[41/96] Building CXX object CMakeFiles\synthizer.dir\src\decoders\wav.cpp.obj
[42/96] Building C object CMakeFiles\buffer_from_raw_data.dir\examples\buffer_from_raw_data.c.obj
[43/96] Building C object CMakeFiles\custom_stream.dir\examples\custom_stream.c.obj
[44/96] Building CXX object CMakeFiles\synthizer.dir\src\pausable.cpp.obj
[45/96] Building C object CMakeFiles\simple_automation.dir\examples\simple_automation.c.obj
[46/96] Building C object CMakeFiles\test_double_refcount.dir\test\double_refcount.c.obj
[47/96] Building CXX object CMakeFiles\synthizer.dir\src\router.cpp.obj
[48/96] Building CXX object CMakeFiles\delay_line_test.dir\test\delay_line.cpp.obj
[49/96] Building CXX object CMakeFiles\test_generation_thread.dir\test\generation_thread.cpp.obj
[50/96] Building CXX object CMakeFiles\test_verify_properties.dir\test\verify_properties.cpp.obj
[51/96] Building CXX object CMakeFiles\synthizer.dir\src\audio_output.cpp.obj
[52/96] Building CXX object CMakeFiles\property_write_bench.dir\benchmarks\property_write.cpp.obj
[53/96] Building CXX object CMakeFiles\synthizer.dir\src\filters\simple_filters.cpp.obj
[54/96] Building CXX object CMakeFiles\synthizer.dir\src\spsc_semaphore.cpp.obj
[55/96] Building CXX object CMakeFiles\synthizer.dir\src\source.cpp.obj
[56/96] Building CXX object CMakeFiles\test_effect_connection.dir\test\effect_connection.cpp.obj
[57/96] Building CXX object CMakeFiles\synthizer.dir\src\streams\memory_stream.cpp.obj
[58/96] Building CXX object CMakeFiles\synthizer.dir\src\streams\custom_stream.cpp.obj
[59/96] Building CXX object CMakeFiles\synthizer.dir\src\background_thread.cpp.obj
[60/96] Building CXX object CMakeFiles\test_noise.dir\test\noise.cpp.obj
[61/96] Building CXX object CMakeFiles\synthizer.dir\src\sources\direct_source.cpp.obj
[62/96] Building CXX object CMakeFiles\test_automation_timeline.dir\test\automation_timeline.cpp.obj
[63/96] Building CXX object CMakeFiles\test_filter_repl.dir\test\filter_repl.cpp.obj
[64/96] Building CXX object CMakeFiles\test_latch.dir\test\latch.cpp.obj
[65/96] Building CXX object CMakeFiles\synthizer.dir\src\sources\panned_source.cpp.obj
[66/96] Building CXX object CMakeFiles\synthizer.dir\src\buffer.cpp.obj
[67/96] Building CXX object CMakeFiles\synthizer.dir\src\effects\fdn_reverb.cpp.obj
[68/96] Building CXX object CMakeFiles\synthizer.dir\src\streams\file.cpp.obj
[69/96] Building CXX object CMakeFiles\synthizer.dir\src\effects\echo.cpp.obj
[70/96] Building CXX object CMakeFiles\synthizer.dir\src\generators\noise.cpp.obj
[71/96] Building CXX object CMakeFiles\synthizer.dir\src\sources\source3d.cpp.obj
[72/96] Building CXX object CMakeFiles\synthizer.dir\src\generators\buffer.cpp.obj
[73/96] Building CXX object CMakeFiles\synthizer.dir\src\context.cpp.obj
[74/96] Building C object CMakeFiles\synthizer_single_file_libs.dir\src\single_file_libs.c.obj
[75/96] Building CXX object CMakeFiles\synthizer.dir\src\generators\streaming.cpp.obj
[76/96] Linking CXX static library synthizer.lib
[77/96] Linking CXX executable test_random_float.exe
[78/96] Linking CXX executable test_generation_thread.exe
[79/96] Linking CXX executable test_filter_repl.exe
[80/96] Linking CXX executable test_latch.exe
[81/96] Linking CXX executable delay_line_test.exe
[82/96] Linking CXX executable test_automation_timeline.exe
[83/96] Linking CXX executable test_double_refcount.exe
[84/96] Linking CXX executable decoding_bench.exe
[85/96] Linking CXX executable property_write_bench.exe
[86/96] Linking CXX executable test_effect_connection.exe
[87/96] Linking CXX executable custom_stream.exe
[88/96] Linking CXX executable events.exe
[89/96] Linking CXX executable test_verify_properties.exe
[90/96] Linking CXX executable basic_stream_handle.exe
[91/96] Linking CXX executable test_noise.exe
[92/96] Linking CXX executable simple_automation.exe
[93/96] Linking CXX executable buffer_from_raw_data.exe
[94/96] Linking CXX executable buffer_from_memory.exe
[95/96] Linking CXX executable load_libsndfile.exe
[96/96] Linking CXX executable file_test.exe
```

Are you saying I *shouldn't* use Clang?

**Comment by ahicks92** [comment]
You're not currently using clang.  Using clang is fine though.  It's sort of outside the scope of this issue, but essentially C++ crashes with things as simple as off-by-ones and whatever but often it does not even though it should and this varies by compiler.  Same with different assembly output and stuff too, so when there's a race condition, sometimes it only shows up under one compiler or the other.

Thanks for all the info.  At this point I can't even ask you for anything else even if I wanted to, so it had better be enough.

**Comment by ahicks92** [comment]
yep, good news, I duplicated it.  Fix at some point.

**Comment by ahicks92** [comment]
Rolling out a point release with this fix in it now.

**Comment by chrisnorman7** [comment]
Sorry, thought I'd commented on this already. Everything works as expected now. Good job (again).
