### ISSUE TITLE
Synthizer seemingly causes issues for other libraries using FFI under Windows

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#81]
When using [dart_synthizer](https://pub.dev/packages/dart_synthizer) from within a flutter project, the [file_picker](https://pub.dev/packages/file_picker) package's [getDirectoryPath](https://pub.dev/documentation/file_picker/latest/file_picker/FilePicker/getDirectoryPath.html) method no longer works.

I don't believe this is a file_picker problem, as the same results are not observed with [dart_sdl](https://pub.dev/packages/dart_sdl), which is a comparable package.

To see this in action:

```shell
flutter create synthizer_breaks
cd synthizer_breaks
flutter pub add dart_synthizer
flutter pub add file_picker
```

Now copy synthizer.dll into the current directory.

Edit the contents of the `lib/main.dart` file to the following:

```dart
// ignore_for_file: avoid_print

import 'package:dart_synthizer/dart_synthizer.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  /// Create an instance.
  const MyHomePage({Key? key}) : super(key: key);

  /// Create state for this widget.
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

/// State for [MyHomePage].
class _MyHomePageState extends State<MyHomePage> {
  /// The synthizer instance.
  Synthizer? synthizer;

  /// The loaded directory.
  String? directory;

  /// Build a widget.
  @override
  Widget build(BuildContext context) {
    final syz = synthizer;
    final String synthizerTitle;
    if (syz == null) {
      synthizerTitle = 'Not created';
    } else if (syz.wasInit) {
      synthizerTitle = 'Initialized';
    } else {
      synthizerTitle = 'Not initialized';
    }
    return Scaffold(
      body: ListView(
        children: [
          ListTile(
            title: const Text('Directory'),
            subtitle: Text(directory.toString()),
            onTap: () async {
              print('Getting directory.');
              final result = await FilePicker.platform.getDirectoryPath();
              print('Directory: $result.');
              setState(() {
                directory = result;
              });
            },
          ),
          ListTile(
            title: const Text('Synthizer instance'),
            subtitle: Text(synthizerTitle),
            onTap: () {
              if (syz == null) {
                print('Creating synthizer.');
                setState(() => synthizer = Synthizer());
              } else if (syz.wasInit == false) {
                print('Initializing synthizer.');
                setState(() => syz.initialize());
              } else {
                print('Nothing to do.');
              }
            },
          ),
        ],
      ),
    );
  }
}
```

I recommend running this with Flutter on the master channel (`flutter channel master & flutter upgrade), as on that channel the UI is more accessible to screen readers.

I read recently that Flutter runs its FFI stuff on a different thread or something, but I've looked for half an hour and can't find the reference. Not sure if that's causing the problem or not.

I'd open an issue against [file_picker](https://github.com/miguelpruivo/flutter_file_picker/issues), but as SDL doesn't cause a crash, I think it's more likely that it's synthizer's problem.

**Comment by chrisnorman7** [comment]
Sorry, realised I forgot to tell you how to reproduce the problem.

If you run the project under desktop (f5 in VS Code or `flutter run -d windows`), you'll get a list view with two items:

The first is the directory name, which you can click on to change the value. It'll bring up the standard windows directory selection dialog.

The other is a button which can be clicked to change the state of Synthizer. I haven't bothered letting it call `syz_shutdown`, since I'm sure you said that synthizer should only be initialized once in a project. If that's changed, then it would solve all my problems.

Anyway, after you've created synthizer, the directory chooser will still pop up. After it's been initialised however, the app just hangs.

Cheers again.

**Comment by ahicks92** [comment]
Are you sure that it's hanging in file_picker?  "This is related to FFI" seems like a big stretch from the info provided, especially since I see a strange two-phase thing where you try to init Synthizer using setState and so on.

If you write a simpler program that initializes Synthizer and then try to run file_picker without any other controls as soon as the window opens, does it hang and if so where?  This doesn't look like a minimal example yet.

Broadly speaking, the only way for Synthizer and file_picker to conflict is if file_picker is using FFI in such a way that it can see the Synthizer DLL and also Synthizer happens to reexport something file_picker is trying to bind.  If this can happen I would be surprised, but also file_picker is partly at fault because you're supposed to be more specific than that with your FFI binding.

You definitely can't re-init Synthizer after it's shut down.  But it would be interesting to find out whether or not shutting it down before you even open your window causes a problem.

Have you tried stepping through your code with a debugger line by line, and seeing which line freezes exactly?

If you're passing `-DCMAKE_MSVC_RUNTIME_LIBRARY` when running the cmake step, dropping that from the command line may prove illuminating.  If you do, don't forget to delete your build directory and start from scratch, otherwise it won't take because of how CMake works.

If you can't get something more minimal for me I'll try to take a look over the weekend or something but at the moment with what you've given taking a look is going to be kind of time-consuming so I'm hoping you can get more first.

**Comment by chrisnorman7** [comment]
Hi,
Thanks for looking over it.

So I wrote it with all those steps to try and demonstrate thoroughly, but I
see now that it might have been too much code. In my actual code, the
initialisation step isn't using `setState`.

I've not tried the line by line thing, that'll be something for me to do
when I'm on my dev machine. I'm 99% sure it's in the file picker line,
because you get the printed message before that line coming in reliably.

I'll do more investigation this evening or so.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
Yeah, you can probably step into the file_picker library too, so if it is freezing there and Dart/Flutter will let you "in file_picker_thing.dart on line 55" is very helpful here.  The scope is otherwise incredibly wide and if I take the "it's FFI conflicting with itself somehow" at face value we immediately jump into some very obscure linker stuff that should hit Python like a wrecking ball because of how Python works, for example.

I don't suppose that lib can be used outside Flutter, in which case you could produce a very straightforward CLI app that produces the behavior?

**Comment by chrisnorman7** [comment]
Unfortunately file_picker can't, no. Honestly, I'm not even sure how those
packages with binary components work, since they use a different package
for each OS or something, and when I tried to view the code for the get
directory thing it is just a single line that raises `UnimplementedError`
(which it's not doing by the way).

I'm not sure when I'll get a chance to look at this, but hopefully soon.

Take care,

Chris Norman

**Comment by chrisnorman7** [comment]
Hi,
I've just tried tackling this again.

So now I have synthizer already loaded and doing useful things. If I use the function that gets the directory name, I get the following error:

```shell
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Error 0x80010106: Cannot change thread mode after it is set.
#0      FilePickerWindows.getDirectoryPath (package:file_picker/src/windows/file_picker_windows.dart:76:25)
#1      _AddAssetState.importDirectory (package:worldsmith_studio/screens/asset_store/add_asset.dart:206:53)
#2      _AddAssetState.build.<anonymous closure> (package:worldsmith_studio/screens/asset_store/add_asset.dart:58:29)
#3      CallbackAction.invoke (package:flutter/src/widgets/actions.dart:534:39)
#4      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:573:21)
#5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:728:38)
#6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:929:20)
#7      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1687:32)
#8      KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:828:34)
#9      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:875:15)
#10     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#11     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
#14     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#15     _rootRun (dart:async/zone.dart:1426:13)
#16     _CustomZone.run (dart:async/zone.dart:1328:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#18     _invoke2 (dart:ui/hooks.dart:189:10)
#19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#20     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#21     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#22     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#23     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
```

I found [this issue](https://github.com/pywinauto/pywinauto/issues/445) which directs me to [this link](https://pywinauto.readthedocs.io/en/latest/HowTo.html#com-threading-model), which seems to suggest both libraries are trying to change the thread model. Is this something I need to report to the author of file picker? Or is it something you need to address in synthizer?

Thanks in advance.

**Comment by chrisnorman7** [comment]
On second thoughts, I created an [issue](https://github.com/miguelpruivo/flutter_file_picker/issues/981) against file_picker anyways, since it seems like something they should know about.

**Comment by ahicks92** [comment]
O it's this.  SO the thing is that I can't fix that on my end.  You've got two things trying to use COM with different threading models and that's not going to work.  I could flip the setting on my side, but then that just makes it so that anything using MTA fails the same way and moves the issue somewhere else.  I don't think there's much to be done here, but I'll leave it open in case someone comes back with a solution.  The way this is supposed to work is that you initialize the COM threading model yourself and none of your libraries do, but that's not practical because e.g. Python doesn't really provide a way to do that (nor does vanilla Dart, to my knowledge).  I'll at least take a quick look this weekend.  It might be possible to fix miniaudio to check if COM is initialized and then not do it, but then you'll run into the problem that using your file_picker dep needs to happen after Synthizer is initialized and on their side they might need STA.

There's reasonably complicated things I could do that come with a pretty big performance hit and a lot of complexity in order to isolate Synthizer COM usage to another thread, but it's too complicated for me to really justify  it for Dart.  You can fix this yourself by getting Synthizer to happen on a dedicated OS thread (or file_picker, whichever).

For background the way this is supposed to work in theory is that you initialize COM in your app and then use libraries, not have your libraries do it.  But this is the real world in which almost no language provides a way to do that, so everyone initializes it for you.  Still, I'm surprised there's a mismatch.  But in any case I don't think that Synthizer can switch to STA.  I'll look into that as well this weekend, but I think that mandates a message loop and then e.g. command line apps fall down.  It's literally been years since I've had to dig into COM directly, but I'll be able to determine if there's a reasonable next step fairly quickly once I have some time to read docs.

**Comment by chrisnorman7** [comment]
That's fine mate, thanks for the detailed reply.

Definitely don't make any special dispensation for Dart, especially when I
could just stop using file_picker.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
All right so the short version is no, there's nothing we can do, not with the bandwidth I have.

The longer version is that we can in theory move all calls into miniaudio to threads not owned by the application.  But that's a bad idea because it's hard to get right and hard to verify that we have full coverage.  In fact if I'm being honest I don't think that Synthizer can even run if you happen to choose the STA first.  It might, it's unclear when COM is going to get mad or just work even though docs say it shouldn't.  By my current understanding it turns into a giant hellscape to get it working and keep it working over time.

Miniaudio can be made to use the STA but if any of the wasapi interfaces need marshalling that disables multi-threading support and, to be honest, I'm surprised that it even works by itself.  Possible they haven't done heavy testing, or that I'm missing the required marshalling in the giant single-file header of death.

background info here: https://docs.microsoft.com/en-us/windows/win32/com/processes--threads--and-apartments

The really short version is "single-threaded apartments are weird and add a bunch of requirements".  I'd start by figuring out why whatever other libraries are involved need the STA, or if that's even what's going on on their side.

**Comment by chrisnorman7** [comment]
OK, thant's fine. I'm still waiting to hear back from the authors of file_picker.

As there's nothing you can do, and it sounds like to do something would cause far more problems than it would solve, I'll close this.
